src/main/java/org/springframework/retry/annotation/CircuitBreaker.java
`@CircuitBreaker` is introduced since not 1.1 but 1.2
=> Fix wrong javadoc

pom.xml, src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java, src/main/java/org/springframework/retry/annotation/Retryable.java, src/test/java/org/springframework/retry/annotation/PrototypeBeanTests.java
Previously, if a bean annotated with `@Retryable` and `@Recover` was
scoped "prototype", the `@Recover` method in the first instance was
called instead of the method in the same instance as the failed `@Retryable`
method.
This was because the delegate cache in `AnnotationAwareRetryOperationsInterceptor`
was keyed only on the `Method` object.
Change the cache to cache at the `targetObject.method` level.
Also fixes `backoff` javadocs.
Fixes https://github.com/spring-projects/spring-retry/issues/93
=> Fix @Recover for Prototype Scoped Beans

src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/test/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandlerTests.java
Related to https://github.com/spring-projects/spring-retry/issues/85
When locating the closest `@Recover` method and there are multiple matching `@Recover` methods, choose the `@Recover` method that matches based on the number of parameters and the types of the parameters (to avoid `java.lang.IllegalArgumentException: argument type mismatch`)
=> Locate matching @Recover based on the number of parameters

pom.xml
Since aspectjrt is included by aspectjweaver, if there's already aspectjweaver then aspectjrt becomes unnecessary.
=> remove aspectjrt

README.md
Applying retry handling declaratively using annotations `@EnableRetry` and `@Retryable` adds a runtime dependency on AspectJ classes (module org.aspectj:aspectjweaver), without which a `NoClassDefFoundError` is thrown on application startup. 
I hit this problem when I added Spring Retry to my existing project, and it took longer than it should to find out how best to resolve the dependency. Given using annotations is likely to be one of the most popular ways of applying retry (and its shown in the 'Quick Start' section), I suspect a lot of people have already and will hit the same problem.
A couple of issues (#30 and #44) have been raised in the past to report this, that were closed with the response that the AspectJ dependency would not be added to the project as it was optional. Can I …
=> Document @Retryable's additional runtime dependency and advice on how it's best resolved.

pom.xml, src/test/resources/org/springframework/retry/interceptor/retry-transaction-test.xml
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://www.springframework.org/schema/aop/spring-aop-2.0.xsd with 1 occurrences migrated to:  
https://www.springframework.org/schema/aop/spring-aop-2.0.xsd ([https](https://www.springframework.org/schema/aop/spring-aop-2.0.xsd) result 200).
* http://www.springframework.org/schema/beans/spring-beans-2.0.xsd with 1 occurrences migrated to:  
https://www.springframework.org/schema/beans/spring-beans-2.0.xsd ([https](https://www.springframework.org/schema/beans/spring-beans-2.0.xsd) result …
=> URL Cleanup

README.md, pom.xml, src/main/java/org/springframework/retry/interceptor/MethodInvocationRetryCallback.java, src/main/java/org/springframework/retry/interceptor/RetryOperationsInterceptor.java, src/main/java/org/springframework/retry/interceptor/StatefulRetryOperationsInterceptor.java, src/main/java/org/springframework/retry/listener/MethodInvocationRetryListenerSupport.java, src/main/java/org/springframework/retry/support/RetryTemplateBuilder.java, src/test/java/org/springframework/retry/annotation/CircuitBreakerTests.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java, src/test/java/org/springframework/retry/annotation/EnableRetryWithBackoffTests.java, src/test/java/org/springframework/retry/interceptor/RetryOperationsInterceptorTests.java, src/test/java/org/springframework/retry/listener/MethodInvocationRetryListenerSupportTests.java
Expose the MethodInvocation in the MethodInvocationRetryCallback in order to permit to concrete RetryListener implementations to inspect in detail the method called as well as its arguments. This information can be used in the retry listener for either detailed logging or monitoring for the proxied method invocations.
This pull-request has emerged based on the discussions held in #119 for the need of exposing detailed information about the AOP intercepted methods on which the spring-retry logic is being applied.
=> Expose the MethodInvocation in the MethodInvocationRetryCallback 

README.md
An example of fluent API usage is added to readme, following #153
=> Readme for fluent template configuration

src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/test/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandlerTests.java
Fix bug when there are multiple recover methods and a potential inheritance with argument types like List.
Issue https://github.com/spring-projects/spring-retry/issues/174#issue-441125555
=> Fix recovering with inheritance on argument types

src/main/java/org/springframework/retry/backoff/ExponentialRandomBackOffPolicy.java, src/test/java/org/springframework/retry/backoff/ExponentialRandomBackOffPolicyTests.java
Fix #126 -- Clearer documentation on what ranges are possible in the example, check to enforce maxInterval so the random multiplication step cannot exceed it.
Pivotal CLI signed for a previous Spring project. Contribution on behalf of Comcast Corporation.
Contribution on behalf of Comcast Corporation.
=> Fix #126 clearer documentation, enforce maxInterval value, tests

README.md, src/main/java/org/springframework/retry/annotation/Recover.java, src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/main/java/org/springframework/retry/annotation/Retryable.java, src/test/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandlerTests.java
> Why not introduce a recoveryName attribute in the `@Retry(recoverName="recover1")` annotation that can then be matched in the `@Recover(name="recover1"...)` annotation? Using parameter names gets super confusing and isn't clear, which forces developers to have to do more testing of the framework just to ensure they have set it up right.
https://github.com/spring-projects/spring-retry/issues/85
**Examples of usage**
``` java
protected static class RecoverByRetryableName {
@Retryable(recoverName = "barRecover")
public int foo(String name) {
return 0;
}
@Recover
public int fooRecover(Throwable throwable, String name) {
return 1;
}
@Recover
public int barRecover(Throwable throwable, String name) {
return 2;
}
}
```
**Current implementation steps**
1.  Added recover name in Retryable …
=> Allow recover by name in `Retryable` annotation.

src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java
Recently, i needed to combine the behavior of `@Retryable` annotation with Spring's `@Transactional` (in order to create  transactional methods that could be auto-retried in case some errors occurred).
So i created a **composed annotation** named `@RetryableTransactional`, which is defined as such:
```
/**
* A meta-annotation that combines {@literal @}{@link Retryable} and {@literal @}{@link Transactional}.
* 
*/
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Retryable 
@Transactional
public @interface RetryableTransactional {
// allow overriding attributes of @Retryable : DOEST WORK, BECAUSE OF USAGE OF AnnotationUtils.findAnnotation()
/**
* @see Retryable#interceptor()
* @return
*/
@AliasFor(annotation = Retryable.class)
String …
```
=> Allow composing `Retryable` annotation with other annotations

src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java, src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/test/java/org/springframework/retry/annotation/CircuitBreakerTests.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
Similar to https://github.com/spring-projects/spring-retry/pull/37
`@Recover` is only detected on interfaces for JDK proxies whereas
`@Retryable` is found on the target class if not on the interface.
=> Find @Recover/CB on target class with JDK proxy

src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
Fixes #197. Even with the changes from #124, recovery methods that are not defined in the interface are not found. I've tested my suggested change, replacing `failingMethod.getDeclaringClass()` with `target.getClass()`. No unit tests failed with this change 🤞.
=> Support @Recovery method that is not defined in interface

src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/test/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandlerTests.java
This allows for the annotations to be used on an interface and still be able to get the retryable name for the failure method.
=> Use AnnotationUtils for retryable name

src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/main/java/org/springframework/retry/interceptor/RetryOperationsInterceptor.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/244
The `RecoverAnnotationRecoveryHandler` only has access to the undecorated
raw bean.
Use the `RetryContext` to make the proxy (if CGLIB) available to the recoverer.
=> GH-244: Invoke Proxy for @Recover Method

src/main/java/org/springframework/retry/annotation/RetryConfiguration.java
This suppresses the info message "Bean 'org.springframework.retry.annotation.RetryConfiguration' of type [org.springframework.retry.annotation.RetryConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)" during the Spring context start.
Relates to issue #256
=> Mark RetryConfiguration as infrastructure bean

src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java, src/main/java/org/springframework/retry/annotation/Backoff.java, src/main/java/org/springframework/retry/policy/ExpressionRetryPolicy.java, src/main/java/org/springframework/retry/support/RetryTemplateBuilder.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java, src/test/java/org/springframework/retry/support/RetryTemplateBuilderTest.java
- remove unnecessary template delimiters from tests
- make expression handling consistent
- template delimiters should not be needed for any
- fix bean resolution in `@BackOff`
=> Annotation Expression Improvements

pom.xml, src/main/java/org/springframework/retry/annotation/Backoff.java
This PR removes the invocation of spring-javaformat:apply by default. Doing so makes the validate goal irrelevant as apply is going to reformat the code if necessary.
The idea of the plugin is that it should prevent you from pushing something that has formatting violations. Running the build, run the apply goal manually, and amending the commit is the idiomatic way of using this plugin.
=> Do not apply Javaformat by default

.springjavaformatconfig, pom.xml
This commit removes the warnings that Maven emits when building the
effective model of the project. This boils down to locking down plugin
versions.
Because there is no version for javaformat, Maven could decide to use
the latest, which requires extra care to build with Java 8. This commit
upgrades explicitly to the latest and configure it to be compatible
with Java 8
=> Remove Maven warnings

ci/README.adoc, ci/config/changelog-generator.yml, ci/config/release-scripts.yml, ci/images/README.adoc, ci/images/ci-image/Dockerfile, ci/images/get-jdk-url.sh, ci/images/setup.sh, ci/parameters.yml, ci/pipeline.yml, ci/scripts/build-project.sh, ci/scripts/common.sh, ci/scripts/generate-changelog.sh, ci/scripts/promote.sh, ci/scripts/stage.sh, ci/tasks/build-ci-image.yml, ci/tasks/build-pr-project.yml, ci/tasks/build-project.yml, ci/tasks/generate-changelog.yml, ci/tasks/promote.yml, ci/tasks/stage.yml
This commit provides an integration with Concourse. A sample pipeline has been deployed to https://ci.spring.io/teams/spring-retry/pipelines/spring-retry-1.3.x (private for now).
The pipeline runs the build for every commit and publishes a new snapshot on `repo.spring.io/snapshot`. There is also a standard release pipeline to release the bits to Maven Central and generate a changelog automatically based on the current labels. If we decide to harmonize the labels, we'd need to change the configuration.
=> Move CI to Concourse

src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java, src/main/java/org/springframework/retry/backoff/BackOffPolicyBuilder.java, src/test/java/org/springframework/retry/backoff/BackOffPolicyBuilderTests.java
`BackOffPolicyBuilder` implementation to expose `BackOffPolicy` building logic to other projects.
A few quick considerations.
My main goals here were consistency with the rest of the project, and reduced risk of breaking behaviors.
That impacted a few decisions, such as:
* I didn't change anything in the actual algorithm to reduce risk of accidentally changing any behavior
* I used `primitives` instead of their classes counterparts (`Long`, `Double`, `Boolean`)
Using classes we'd be able to set a value only if not `null`, delegating to the policy which default value to use. But we'd have to introduce null checks all around, which might interfere the first bullet above. Also, this helps keeping consistency with the rest of the project.
* No validation if the inputs are `> 0`. If these …
=> GH-276: Expose BackOffPolicy building logic

pom.xml, src/test/java/org/springframework/retry/support/RetryTemplateTests.java
EasyMock was only used in one test.
=> Replace EasyMock with Mockito

README.md, src/main/java/org/springframework/retry/RetryListener.java, src/main/java/org/springframework/retry/listener/MethodInvocationRetryListenerSupport.java, src/main/java/org/springframework/retry/support/RetryTemplate.java, src/test/java/org/springframework/retry/interceptor/RetryOperationsInterceptorTests.java, src/test/java/org/springframework/retry/support/RetryTemplateTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/231
Enhance `RetryListener` to allow it to examine the result to determine
whether the call should be accepted, or retried according to the retry
policy.
=> GH-231: Support Retry Based on Result

src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java, src/test/java/org/springframework/retry/annotation/CircuitBreakerTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/293
**cherry-pick to 1.3.x**
=> GH-293: Fix Bean Resolver for CBreaker Expressions

src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java, src/test/java/org/springframework/retry/annotation/DontRetryRecovererTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/299
Caused by the fix for #244, recover methods should not be considered
as retryable, with class level annotation.
**cherry-pick to 1.3.x**
=> GH-299: Fix @Recover with Class Level @Retryable

src/main/java/org/springframework/retry/policy/SimpleRetryPolicy.java
@pivotal-cla This is an Obvious Fix
Just fixed a javadoc in the `SimpleRetryPolicy`.
=> Fix javadoc

README.md, src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/test/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandlerTests.java
Creating a custom annotation composing `@Retryable` will not get the actual recover argument value even when the recover method is annotated with `@AliasFor`. Eg:
```
@Target({ ElementType.METHOD, ElementType.TYPE })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Retryable(maxAttempts = 4)
public @interface ComposedRetryable {
@AliasFor(annotation = Retryable.class, attribute = "recover")
String recover() default "";
}
```
The reason is that `RecoverAnnotationRecoveryHandler` is still using AnnotationUtils.findAnnotation() instead of AnnotatedElementUtils.findMergedAnnotation()
=> Allow composing `@Retryable` annotation with @AliasFor recover method 

src/main/java/org/springframework/retry/annotation/EnableRetry.java
Any Spring application that uses the annotation `@EnableRetry` with Spring Framework 6.0.0 and Spring Retry 2.0.0 logs the following warning on start-up:
> WARN org.springframework.core.annotation.AnnotationTypeMapping [main] : Support for convention-based annotation attribute overrides is deprecated and will be removed in Spring Framework 6.1. Please annotate the following attributes in @org.springframework.retry.annotation.EnableRetry with appropriate @AliasFor declarations: [proxyTargetClass]
This PR does what the warning kindly asks for.
The warning can be seen easiest when executing `EnableRetryTests`.
I've also assembled a reproducer. It's a plain Spring Boot app with the annotation: https://github.com/hpoettker/alias-demo
=> Annotate `@EnableRetry` with `@AliasFor`

src/main/java/org/springframework/retry/annotation/CircuitBreaker.java, src/main/java/org/springframework/retry/annotation/Retryable.java, src/test/java/org/springframework/retry/annotation/CircuitBreakerResetTimeoutTests.java, src/test/java/org/springframework/retry/annotation/CircuitBreakerTests.java
This is a follow-up on #322. Sorry for bothering you twice!
Using the annotation `@CircuitBreaker` with Spring Framework 6 leads to the following warning:
> WARN org.springframework.core.annotation.AnnotationTypeMapping [main] : Support for convention-based annotation attribute overrides is deprecated and will be removed in Spring Framework 6.1. Please annotate the following attributes in @org.springframework.retry.annotation.CircuitBreaker with appropriate @AliasFor declarations: [include, maxAttempts, noRetryFor, maxAttemptsExpression, notRecoverable, exclude, exceptionExpression, label, retryFor]
It can be seen e.g. when running `CircuitBreakerTests`.
I also took the liberty to mark `CircuitBreaker::value` as deprecated because the field `Retryable::value` that it's aliasing is also …
=> AnnotationTypeMapping warning when using `@CircuitBreaker` with Spring Framework 6

README.md, src/main/java/org/springframework/retry/RetryListener.java, src/main/java/org/springframework/retry/listener/RetryListenerSupport.java, src/main/java/org/springframework/retry/stats/StatisticsListener.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java, src/test/java/org/springframework/retry/annotation/EnableRetryWithListenersTests.java, src/test/java/org/springframework/retry/interceptor/RetryOperationsInterceptorTests.java, src/test/java/org/springframework/retry/interceptor/StatefulRetryOperationsInterceptorTests.java, src/test/java/org/springframework/retry/listener/RetryListenerSupportTests.java, src/test/java/org/springframework/retry/listener/RetryListenerTests.java, src/test/java/org/springframework/retry/stats/StatisticsListenerTests.java, src/test/java/org/springframework/retry/support/RetryTemplateTests.java
With Spring Retry 2.0.0, the baseline was lifted from Java 6 to Java 17, which allows to now use default implementations in interfaces.
The only purpose of `RetryListenerSupport` is to provide default implementations for `RetryListener`. As such support implementations are no longer required, this PR deprecates `RetryListenerSupport` and adds its default implementations to `RetryListener`.
=> Add default implementations to `RetryListener`

NOTICE.txt, pom.xml
In many other Spring and Spring Boot projects, the license and notice files are included in the jar file under META-INF. In this Spring project, the two files should also be added to the jar.
=> add notice and license to jar

src/main/java/org/springframework/retry/annotation/EnableRetry.java, src/main/java/org/springframework/retry/annotation/RetryConfiguration.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
=> Introduce order for @EnableRetry

src/main/java/org/springframework/retry/annotation/EnableRetry.java
The new default order is `Ordered.LOWEST_PRECEDENCE - 1` to make sure the advice is applied before other advices with
`Ordered.LOWEST_PRECEDENCE` order (e.g. an advice responsible for `@Transactional` behavior).
See also https://github.com/spring-projects/spring-retry/pull/333#pullrequestreview-1330977780
=> Change default order for @EnableRetry

src/main/java/org/springframework/retry/backoff/BackOffPolicyBuilder.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/340
Runtime evaluation of `delayExpression` with a `FixedBackOffPolicy` was not implemented causing the expression to be ignored.
=> GH-340: Fix delayExpression w/ FixedBackOffPolicy

src/main/java/org/springframework/retry/policy/TimeoutRetryPolicy.java, src/test/java/org/springframework/retry/policy/TimeoutRetryPolicyTests.java
Adds a separate constructor to `TimeoutRetryPolicy` to create a new instance with a configurable timeout. This follows the pattern established by other policies, for example, `SimpleRetryPolicy`, that allow to customise their behaviour during instance creation.
=> Add constructor make timeout customisable

src/main/java/org/springframework/retry/support/RetryTemplateBuilder.java, src/test/java/org/springframework/retry/support/RetryTemplateBuilderTests.java
While working on `RestTemplateBuilder`, I noticed a couple of typos, some confusing explanations, a lack of descriptions of error conditions, and that it does not always follow the Spring Framework style guide. So I tried my best to improve it.
If you're not happy with some choices I made, feel free to edit it yourself.
=> Overhaul Javadoc of RestTemplateBuilder

src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
According to Javadoc of @Recover, The Throwable first argument is optional. Before this commit,
```
java.lang.NullPointerException: Cannot invoke "java.lang.Class.isAssignableFrom(java.lang.Class)" because "meta.type" is null
at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.findClosestMatch(RecoverAnnotationRecoveryHandler.java:154)
at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.recover(RecoverAnnotationRecoveryHandler.java:75)
at org.springframework.retry.interceptor.RetryOperationsInterceptor$ItemRecovererCallback.recover(RetryOperationsInterceptor.java:159)
at org.springframework.retry.support.RetryTemplate.handleRetryExhausted(RetryTemplate.java:543)
at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:389) …
```
=> Throwable as first argument of explicit recover method should be optional

README.md, src/main/java/org/springframework/retry/support/RetrySynchronizationManager.java, src/test/java/org/springframework/retry/annotation/EnableRetryNoThreadLocalTests.java, src/test/java/org/springframework/retry/annotation/EnableRetryWithBackoffNoThreadLocalTests.java, src/test/java/org/springframework/retry/support/RetrySynchronizationManagerNoThreadLocalTests.java, src/test/java/org/springframework/retry/support/RetryTemplateNoThreadLocalTests.java
* Add an option to store contexts in a map instead of a `ThreadLocal`
* Subclass existing tests to verify functionality
=> Add Option to Avoid Use of ThreadLocal

src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java, src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/383
If explicit exceptions are referenced, and an `exceptionExpression` is provided, the `maxAttemptsExpression` was ignored.
=> GH-383: maxAttemptsExpression Ignored Sometimes

src/main/java/org/springframework/retry/backoff/ExponentialBackOffPolicy.java, src/main/java/org/springframework/retry/backoff/FixedBackOffPolicy.java, src/main/java/org/springframework/retry/backoff/UniformRandomBackOffPolicy.java, src/test/java/org/springframework/retry/backoff/ExponentialBackOffPolicyTests.java, src/test/java/org/springframework/retry/backoff/FixedBackOffPolicyTests.java, src/test/java/org/springframework/retry/backoff/UniformRandomBackOffPolicyTests.java
=> GH-386: Restore interrupted thread status in provided backoff policies

src/main/java/org/springframework/retry/annotation/Backoff.java
Resolves https://github.com/spring-projects/spring-retry/issues/391
=> GH-391: More Javadoc Polishing

src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java, src/main/java/org/springframework/retry/annotation/Retryable.java, src/test/java/org/springframework/retry/annotation/EnableRetryWithListenersTests.java
Hey folks,
I was evaluating this library in detail for the use in our enterprise project and came across an issue that seemed rather trivial to carry out an implementation for as per @artembilan's suggestion here: https://github.com/spring-projects/spring-retry/issues/211#issuecomment-1761945504. 
To the best of my knowledge this implementation is fully reverse-compatible.
Please refer to GH-211 for more context if necessary.
upd: made a few corrections that felt right after a good night's sleep 😄
=> GH-211: Provide the ability to exclude global retryListeners

src/main/java/org/springframework/retry/RetryContext.java
Both `getParent()` and `getLastThrowable()` might return null, as mentioned in javadoc. `@Nullable` helps an IDE warns developers about potential NPE.
It is a reminiscence of the problem, I've encountered recently, incorrectly assuming that `onSuccess` will only be executed if there was at least failed attempt before (which resulted in no throwable and NPE).
=> Add @Nullable in RetryContext to easier detect possible NPE

README.md, pom.xml, src/main/java/org/springframework/retry/support/MetricsRetryListener.java, src/test/java/org/springframework/retry/support/RetryMetricsTests.java
=> GH-458: Introduce `MetricsRetryListener`

src/main/java/org/springframework/retry/backoff/UniformRandomBackOffPolicy.java, src/test/java/org/springframework/retry/backoff/UniformRandomBackOffPolicyTests.java
When maxBackOffPeriod is less than minBackOffPeriod, delta is taken taken as zero in UniformRandomBackOffPolicy backOff method.
=> Fix backOff API in UniformRandomBackOffPolicy

src/main/java/org/springframework/retry/support/RetryTemplate.java, src/main/java/org/springframework/retry/support/RetryTemplateBuilder.java, src/test/java/org/springframework/retry/support/RetryTemplateBuilderTests.java, src/test/java/org/springframework/retry/support/RetryTemplateTests.java
fixes: https://github.com/spring-projects/spring-retry/issues/470
Because there is no Auto-Configuration I think it is fine to just add the hint without restrictions or class checks.
=> feat: setter for logger field of RetryTemplate

src/main/java/org/springframework/retry/annotation/RetryConfiguration.java
This pull request introduces a default implementation of `hashCode` for `RetryConfiguration.AnnotationClassOrMethodPointcut`.
I discovered that using Spring Cloud with configuration refreshing (specifically the `@RefreshScope` annotation and `ConfigServicePropertySourceLocator` as part of spring-cloud-config) can lead to a "java.lang.OutOfMemoryError: Metaspace". This occurs because the `ConfigServicePropertySourceLocator` is re-initialized with every refresh. Due to the absence of a `hashCode` implementation, proxies for this class are regenerated each time, which causes them to be stored in the `org.springframework.cglib.core.internal.LoadingCache` (with `RetryConfiguration.AnnotationClassOrMethodPointcut` being part of the composite key for this object). 
This results in an excessive …
=> Add default hashCode implementation to RetryConfiguration.AnnotationClassOrMethodPointcut

.github/actions/build/action.yml, pom.xml
Fixes: https://github.com/spring-projects/spring-retry/issues/480
* Add `flatten-maven-plugin` to resolve properties and remove unnecessary build info from the final POM of the artifact to install/deploy
=> GH-480: Bring back POM `revision` property

src/main/java/org/springframework/retry/interceptor/RetryOperationsInterceptor.java, src/test/java/org/springframework/retry/interceptor/RetryOperationsInterceptorTests.java
* Changed removeAttribute to use the same key as setAttribute("___proxy___").
* Fixed an issue where a proxy reference remained in the context due to the previous "__proxy__" key mismatch. 
Found a small bug: I might be mistaken, but I think the proxy key mismatch is preventing removal. Please have your team take a look when you have a moment. Thanks!
=> Fix proxy attribute name mismatch in RetryOperationsInterceptor

src/main/java/org/springframework/retry/backoff/ExponentialBackOffPolicy.java, src/test/java/org/springframework/retry/backoff/ExponentialBackOffPolicyTests.java
This PR addresses #352 by adding warning logs when invalid values are provided to ExponentialBackoffPolicy setters.
- Added warning logs in `setInitialInterval()` when value < 1
- Added warning logs in `setMultiplier()` when value <= 1.0
- Added warning logs in `setMaxInterval()` when value <= 0
The current implementation silently adjusts invalid values without informing users. This can lead to confusion when configured values differ from actual behavior. Adding warning logs helps users understand when their configuration needs adjustment.
This change maintains backward compatibility by:
- Keeping the existing behavior of silently adjusting invalid values
- Only adding warning logs to inform users
- No breaking changes to the API
Closes #352
=> Add warnings for invalid setter values in ExponentialBackoffPolicy
