- README.md
- src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java
- src/main/java/org/springframework/retry/annotation/Backoff.java
- src/main/java/org/springframework/retry/annotation/Retryable.java
- src/main/java/org/springframework/retry/policy/ExpressionRetryPolicy.java
- src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
> Add Expression Support to @Retryable

- README.md
- src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java
- src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
> GH-34: Resolve Placeholders in Expressions

- src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java
- src/test/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandlerTests.java
Created this PR in order to have a recover method where the return class is a parent class or interface of the failing method return type.
> Recover method with return parent class

- src/main/java/org/springframework/retry/annotation/Backoff.java
Improve a previous PR by removing all of the git weirdness
> Fix the Backoff.java docs even more

- src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java
- src/main/java/org/springframework/retry/annotation/CircuitBreaker.java
- src/test/java/org/springframework/retry/annotation/CircuitBreakerTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/123
> GH-123: Expressions for CircuitBreaker Properties

- pom.xml
> #114 - Upgrade Spring to version 5.0.7

- src/main/java/org/springframework/classify/SubclassClassifier.java
- src/test/java/org/springframework/classify/SubclassExceptionClassifierTests.java
See https://github.com/spring-projects/spring-retry/issues/121
> TreeSet not always correctly sorted for "Uncomparable" exceptions

- src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java
- src/test/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandlerTests.java
Multiple recovery methods creating an ArrayIndexOutOfBoundsException. Fixed #145
> Multiple recovery methods creating an ArrayIndexOutOfBoundsException. Fixed #145

- src/main/java/org/springframework/retry/support/RetryTemplate.java
- src/test/java/org/springframework/retry/interceptor/RetryOperationsInterceptorTests.java
- useful when framework code needs to add a listener before user
listeners.
> Support positional RetryListeners

- README.md
Edited for spelling, punctuation, usage, and corporate voice.
Also added an external link and a cross-reference.
> Editing pass

- README.md
The imperative example shows the imperative style.
> Fixed wording

- README.md
- src/main/java/org/springframework/retry/annotation/RecoverAnnotationRecoveryHandler.java
- src/main/java/org/springframework/retry/annotation/RetryConfiguration.java
- src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/237
- also don't include non-singletons or perform eager inits
- `spring-javaformat` has reformatted some other code
> GH-237: Fix Multiple RetryListeners for @Retryable

- src/main/java/org/springframework/retry/support/RetryTemplateBuilder.java
- src/test/java/org/springframework/retry/support/RetryTemplateBuilderTest.java
GH-254: Nice to have: notRetryOn() and retryOn() in RetryTemplateBuilder
Fixes https://github.com/spring-projects/spring-retry/issues/254
Add method with list parameter by overloading existed method
> Fixes GH-254

- src/test/java/org/springframework/retry/support/RetryTemplateBuilderTest.java
It's fine in my IDE, but doesn't look good in git..
- IDE
- git
Linked pull request : https://github.com/spring-projects/spring-retry/pull/255
> Fix indent

- pom.xml
This removes some additional warnings in the build.
> Specify file source encoding

- src/test/java/org/springframework/retry/annotation/CircuitBreakerTests.java
- src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
- src/test/java/org/springframework/retry/interceptor/RetryOperationsInterceptorTests.java
- src/test/java/org/springframework/retry/interceptor/StatefulRetryOperationsInterceptorTests.java
- src/test/java/org/springframework/retry/listener/MethodInvocationRetryListenerSupportTests.java
- src/test/java/org/springframework/retry/listener/RetryListenerTests.java
- src/test/java/org/springframework/retry/support/RetryTemplateTests.java
Missed a few in the last commit.
> GH-288: More AssertJ Changes

- README.md
- src/main/java/org/springframework/retry/RetryContext.java
- src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java
- src/main/java/org/springframework/retry/annotation/CircuitBreaker.java
- src/main/java/org/springframework/retry/annotation/Retryable.java
- src/main/java/org/springframework/retry/policy/SimpleRetryPolicy.java
- src/main/java/org/springframework/retry/support/RetryTemplate.java
- src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
- src/test/java/org/springframework/retry/support/RetryTemplateTests.java
- src/test/java/org/springframework/retry/support/StatefulRecoveryRetryTests.java
Resolves https://github.com/spring-projects/spring-retry/issues/264
> GH-264: Enable Skipping Recovery

- src/main/java/org/springframework/retry/annotation/AnnotationAwareRetryOperationsInterceptor.java
- src/main/java/org/springframework/retry/backoff/BackOffPolicyBuilder.java
- src/main/java/org/springframework/retry/backoff/ExponentialBackOffPolicy.java
- src/main/java/org/springframework/retry/backoff/FixedBackOffPolicy.java
- src/main/java/org/springframework/retry/backoff/UniformRandomBackOffPolicy.java
- src/main/java/org/springframework/retry/policy/CircuitBreakerRetryPolicy.java
- src/main/java/org/springframework/retry/policy/SimpleRetryPolicy.java
Resolves https://github.com/spring-projects/spring-retry/issues/319
Regression: https://github.com/spring-projects/spring-retry/commit/47c1e52900b32dc29fbf54699cfa4c60007b3c01
Multiple setters with different types.
> GH-319: Fix Javabean Setter Collision

- src/main/java/org/springframework/retry/annotation/EnableRetry.java
- src/main/java/org/springframework/retry/annotation/RetryConfiguration.java
- src/test/java/org/springframework/retry/annotation/EnableRetryTests.java
> Backport: Introduce order for @EnableRetry

- src/main/java/org/springframework/retry/policy/CircuitBreakerRetryPolicy.java
https://github.com/spring-projects/spring-retry/issues/403
Haven't had time to look into adding/editing tests, is this a problem?
> Fix null check, remove possible NPE (Issue #403)

- src/main/java/org/springframework/retry/policy/ExpressionRetryPolicy.java
@rmorgan @joshlong @javiereguiluz @trisberg
> fix: Null pointer error may occur

- README.md
> Fix README file pointing to correct version of JDK
